### ISSUE TITLE
ES6 refactoring

### ISSUE THREAD

**Issue by all-bear** [all-bear/react-native.advanced-fetch#1]
For now we export one object from index.js, which is not the ES6 way, we need to refactor it like this:

```javascript
export { versionCachedFetch } from './lib/cached-fetch';
```

so we will be able it import it like this

```javascript
import { versionCachedFetch } from 'react-native-advanced-fetch';
```

**Comment by all-bear** [comment]
Fixed by #7bcc920d9a74067d1e6f0f89be7e657b4155667f

**Comment by KirillPd** [comment]
#7bcc920d9a74067d1e6f0f89be7e657b4155667f

**Comment by KirillPd** [comment]
#1

**Comment by all-bear** [comment]
README need to be updated

**Comment by all-bear** [comment]
Related to #11
